### ISSUE TITLE
md 

### ISSUE THREAD

**Issue by DarrenDsouza7273** [Alistair2522/FinalProject#1]

**Comment by DarrenDsouza7273** [comment]
# Event Harbour: Elevating Collaboration with Committee Dashboards

**Event Harbour** goes beyond conventional event coordination by introducing an advanced Committee Dashboard, elevating the level of collaboration among team members. This feature not only simplifies the planning process but also enhances communication, making it easy for committee members to connect and share ideas seamlessly.

## **Key Features**

### **1. Secure Committee Chat Functionality**

- **Real-Time Communication:** Facilitate real-time discussions with committee members through a secure chat functionality embedded within the Committee Dashboard. This feature eliminates the need for external communication channels, ensuring confidentiality and efficiency.

- **Centralized Collaboration:** All committee communication is centralized, providing a dedicated and organized space for discussions, updates, and decision-making. This centralized approach enhances accountability and clarity.

### **2. Streamlined Event Planning**

- **Task Assignment and Tracking:** Effortlessly assign tasks to committee members and track their progress directly within the Committee Dashboard. This ensures a coordinated effort and transparent task management.

- **Shared Document Repository:** Access a shared repository for documents, files, and resources, fostering collaboration and maintaining a synchronized understanding among committee members.

### **3. Attendee-Focused Calendar Experience**

- **Upcoming Events Visualization:** The integrated calendar feature allows attendees to effortlessly visualize all upcoming events. This comprehensive overview ensures that attendees stay informed and engaged with upcoming activities.

- **Effortless Registration:** Attendees can seamlessly register for events directly through the platform, providing a streamlined and user-friendly registration process.

## **Empowering Committee Collaboration**

Event Harbour's Committee Dashboard is designed to empower committee collaboration, providing an elegant solution for efficient and secure communication. From real-time chat functionality to streamlined event planning tools, our platform is meticulously crafted to enhance collaboration, ultimately bringing your collective vision to life.

## **Getting Started**

To run Event Harbour on your local machine, follow these steps:

1. **Clone the Repository:**
   ```bash
   git clone <repository_url>
   cd <project_directory>
2. **Install the required dependencies:**
   ```bash
   npm install or npm instal --legacy-peer-deps
3. **Run The Back-End:**
   ```bash
   cd client
   client/server/node server.js
4. **Run the Front-End:**
   ```bash
   cd client
   npm run
   npm start

**Comment by Alistair2522** [comment]
Very Nice`
